flowchart LR
  subgraph A["Administrador"]
    Admin["Actor"]
    A0(("Autenticarse"))
    A1(("Usuarios"))
    A2(("Datos maestros"))
    A3(("Horarios IA"))
    A4(("Formularios"))
    A5(("Asignaciones"))
    A6(("KDD"))
    A7(("Auditoria"))
  end

  subgraph D["Docente"]
    Docente["Actor"]
    D0(("Autenticarse"))
    D1(("Consultar horario"))
    D2(("Dashboard"))
    D3(("Recuperar clave"))
  end

  subgraph E["Estudiante"]
    Estudiante["Actor"]
    E0(("Autenticarse"))
    E1(("Consultar horario"))
    E2(("Responder evaluacion"))
    E3(("Inscripcion grupo"))
    E4(("Recuperar clave"))
  end

  Admin --> A0
  Admin --> A1
  Admin --> A2
  Admin --> A3
  Admin --> A4
  Admin --> A5
  Admin --> A6
  Admin --> A7

  Docente --> D0
  Docente --> D1
  Docente --> D2
  Docente --> D3

  Estudiante --> E0
  Estudiante --> E1
  Estudiante --> E2
  Estudiante --> E3
  Estudiante --> E4
